CREATE DATABASE UnterDB;
USE UnterDB;

CREATE TABLE Customer(
id INT NOT NULL AUTO_INCREMENT,
Firstname VARCHAR(128) NOT NULL,
Lastname VARCHAR(128) NOT NULL,
Email VARCHAR(128) NOT NULL,
Password VARCHAR(128) NOT NULL,
Phone VARCHAR(20),
Zip INT NOT NULL,
Deactivated BOOLEAN NOT NULL,
Rating DOUBLE,
PRIMARY KEY (id)
);

CREATE TABLE Driver(
id INT NOT NULL AUTO_INCREMENT,
Phone VARCHAR(20),
Birthday DATE NOT NULL,
LicenseNumber VARCHAR(30) NOT NULL,
LicenseExpires DATE NOT NULL,
Employed BOOLEAN NOT NULL,
UserType_id INT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE SystemUser(
id INT NOT NULL AUTO_INCREMENT,
Firstname VARCHAR(128) NOT NULL,
Lastname VARCHAR(128) NOT NULL,
Email VARCHAR(128) NOT NULL,
Password VARCHAR(128) NOT NULL,
UserType INT(5) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Booking(
id INT NOT NULL AUTO_INCREMENT,
WorkSchedule_id INT,
Customer_id INT NOT NULL,
OrderDate DATETIME NOT NULL,
BookingDate DATETIME NOT NULL,
Shared BOOLEAN NOT NULL,
Approved BOOLEAN NOT NULL, 
ApprovedDate DATETIME,
Completed BOOLEAN NOT NULL,
CompletedTime DATETIME,
TotalAmount DOUBLE,
People INT NOT NULL,
ArrivalTime DATETIME,
ArrivalPoint VARCHAR(128),
CANCELD BOOLEAN NOT NULL,
PRIMARY KEY (id)
);


CREATE TABLE WorkSchedule(
id INT NOT NULL AUTO_INCREMENT,
Taxi_id INT NOT NULL,
Driver_id INT NOT NULL,
StartTime DATETIME,
EndTime DATETIME,
PRIMARY KEY (id)
);

CREATE TABLE Taxi(
id INT NOT NULL AUTO_INCREMENT,
TaxiType_id INT NOT NULL,
LicensePlate VARCHAR(20) NOT NULL,
Brand VARCHAR(128) NOT NULL,
Model VARCHAR(128) NOT NULL,
RegYear INT NOT NULL,
Commissioned DATE NOT NULL,
Active BOOLEAN NOT NULL,
Decommissioned DATE,
InUse BOOLEAN NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE TaxiType(
id INT NOT NULL AUTO_INCREMENT,
Pets BOOLEAN NOT NULL,
TrunkVol VARCHAR(20) NOT NULL,
HandiCap BOOLEAN NOT NULL,
Seats INT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE ActiveTaxi(
id INT NOT NULL AUTO_INCREMENT,
WorkSchedule_id INT NOT NULL,
Free BOOLEAN NOT NULL,
CurrentAddress VARCHAR(256) NOT NULL,
CurrentZip INT NOT NULL,
DestinationAddress VARCHAR(256) NOT NULL,
DestinationZip INT NOT NULL,
DestinationPickup BOOLEAN NOT NULL,
OrderInQueue INT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Rating(
id INT NOT NULL AUTO_INCREMENT,
Booking_id INT NOT NULL,
Rating DOUBLE NOT NULL,
PRIMARY KEY (id)
);


ALTER TABLE Booking
ADD FOREIGN KEY (WorkSchedule_id) REFERENCES WorkSchedule(id),
ADD FOREIGN KEY (Customer_id) REFERENCES Customer(id);


ALTER TABLE WorkSchedule
ADD FOREIGN KEY (Taxi_id) REFERENCES Taxi(id),
ADD FOREIGN KEY (Driver_id) REFERENCES Driver(id);

ALTER TABLE Taxi
ADD FOREIGN KEY (TaxiType_id) REFERENCES TaxiType(id);

ALTER TABLE ActiveTaxi
ADD FOREIGN KEY (WorkSchedule_id) REFERENCES WorkSchedule(id);

ALTER TABLE Rating
ADD FOREIGN KEY (Booking_id) REFERENCES Booking(id);

ALTER TABLE Driver
ADD FOREIGN KEY (UserType_id) REFERENCES SystemUser (id);


